### ISSUE TITLE
Regarding Custom Audio

### ISSUE THREAD

**Issue by DatPanDat** [northwood-studios/SCPSL-Translations#58]
So I was translating some files and stuff into Thai. And I came across a folder called "Custom Audio" in the Russian folder. May I ask if those are files that are used to replace the normal announcement and warnings? And what should I do if I want to try to make and implement my own language into the game?

**Comment by Rnen** [comment]
Ok so i asked around
Apparently after CASSIE was reworked, custom audio files are no longer possible, because CASSIE constructs all announcements from single words (meaning you would have to custom re-record each word in CASSIE, which we dont currently support)
So sadly thats a thing of the past :disappointed:
