### ISSUE TITLE
Error, Testing and Font problem (new Vietnamese translation)

### ISSUE THREAD

**Issue by k4tyu5ha** [northwood-studios/SCPSL-Translations#599]
After finish the text translation and test it in the game, I've encountered some issues. The first problem is the font, the font in the game makes marked letter look weird (example: the word 'Khán giả' which means spectator appeared in the game with two letter 'á' and 'ả' become very big beside usual size of unmarked letter. The second issue is error that makes the game crash when browsing server (The instruction at 0x00007FFA0E63E607 referenced memory at 0x000001914AA8D000. The memory could not be read). Hope to get the reply soon, thanks in advance!

**Comment by k4tyu5ha** [comment]
![Screenshot (937)](https://user-images.githubusercontent.com/70190441/91169095-e965ca80-e700-11ea-98c6-f984f9a6d534.png)
The screenshot of the error is here

**Comment by OneKoin** [comment]
I can't help you about the font issue but,

First, this isn't tech-support channel. if you have a problem with game unrelated to translation or fonts, go to scp sl official discord's #tech-support channel for help.

Second, that issue is known. Try changing graphics api settings to default/auto. If your game keep crashes before you can change settings, try SCPSLSettingChanger.exe
[Download](https://cdn.discordapp.com/attachments/738398183842906217/738398215744913509/SCPSLSettingChanger.exe)

**Comment by k4tyu5ha** [comment]
The main problem now is the font problem. The graphic issue seems to happen before I put my translation in, forgot to not mention it here, my bad (It doesn't affect much anyway). I just want to fix the font, but I will need to wait for some patches before getting the fix, thanks for your reply.
