### ISSUE TITLE
NewInvetory.txt Missing Description

### ISSUE THREAD

**Issue by superorangejuice** [northwood-studios/SCPSL-Translations#72]
O5-level Keycard and Chaos Insurgency Access Device are missing a description entirely. Every other item either has "No description" or a unique description.

**Comment by Dat-Joseph** [comment]
There's a simple reason for this. If you open the Inventory and hover with your mouse over each item it doesnt show any description.
Example would be keycards, there is no description for them because there is none shown when hovering over them. You can try it out but it wont show anything even if you add a description.
I did add descriptions for each item just to be sure for the future. They arent used yet though.
Heres an example:
https://github.com/northwood-studios/SCPSL-Translations/blob/master/Translations/de/NewInventory.txt#L14
Line of Translation ^
https://youtu.be/Iimts49SO5U
Example ingame ^

**Comment by Dat-Joseph** [comment]
Seems the issue is solved
